title: My Blog
theme: minima
minima:
  header_pages:
   - about.md
  date_format: "%b %-d, %Y"
# theme: jekyll-theme-cayman
# theme: jekyll-theme-chirpy # failed
# remote_theme: cotes2020/jekyll-theme-chirpy # failed

# plugins:
# - jekyll-remote-theme
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-archives
# - jekyll-sitemap
